### ISSUE TITLE
allow controlled connections outside of localhost

### ISSUE THREAD

**Issue by balejk** [meejah/fowl#37]
Imagine I have a machine which I can access on a certain port on the local network which I share with machines of other people. I leave the network and want to connect to my machine from the internet, however that is not directly possible. I would thus like to ask somebody on the network to use their machine to tunnel me to mine, that is, instruct them to run fowl which will allow me to connect on one port and be forwarded through their machine onto the local network address and port of my machine. At the same time I want to be able to disallow the proxy to open any other ports on my side because I might not necessarily fully trust it.

As far as I understand the documentation, this is not currently directly possible because only localhost connections can be allowed (or all connections with no restrictions). As a workaround, it might be possible to set up some additional forwarding on the proxying machine, for instance via netcat, however, a direct support would be preferable.

**Comment by meejah** [comment]
So, _technically_ speaking there is no problem with your desired setup.

The reason I went with "localhost-only" for the first cut of a "policy" API is because it's simple, and relatively safe. It also allows for simpler CLI options with just port numbers.

All that said, it would be nice to support more options.

One way to achieve this while being very flexible might be an "ask on every listener" option? That is, whenever your side is asked to listen, the "Twisted endpoint string" is presented via the API. A basic UX treatment could just show this to the user -- or a fancier one could try to describe it.

Note that the permissions are "asymmetric" as in each side decides themselves. So you could have "do whatever" mode on the far side, but "no listeners at all" on your side.

**Comment by balejk** [comment]
> The reason I went with "localhost-only" for the first cut of a "policy" API is because it's simple, and relatively safe. It also allows for simpler CLI options with just port numbers.

I understand, but it doesn't seem like allowing to specify an arbitrary
endpoint string instead of a port which would then be compared with the
other side's request and if allowed passed to Twisted would add too much
complexity, or would it?

> One way to achieve this while being very flexible might be an "ask on every listener" option? That is, whenever your side is asked to listen, the "Twisted endpoint string" is presented via the API. A basic UX treatment could just show this to the user -- or a fancier one could try to describe it.

I don't see how this would be different/more complex from being able to
whitelist endpoints beforehand on the command line. This sounds like a
good solution for the interactive TUI, but I think it should be possible
to use the CLI without interactivity -- for instance, what I have done
in the past is run fowl on one machine, write down the code and then
travel to another machine and connect from there, I wouldn't be able to
return and confirm the listen/connect requests interactively in those
cases.

> Note that the permissions are "asymmetric" as in each side decides themselves. So you could have "do whatever" mode on the far side, but "no listeners at all" on your side.

Indeed, I wondered whether that might work too, however I believe that
ideally, both sides should be able to set restrictions.

**Comment by meejah** [comment]
Yeah, one API treatment could indeed just be to list literal Twisted endpoint strings (on both sides).

A big reason I didn't do that straightaway is that they're a little obscure, and also I've not thought hard about what kinds of shenanigans one might get up to with them. Perhaps I just over-thinking it.

Another issue is correspondences between the listener and the connector. That is, "the same port" or "a different port" is kind of easy to think about, but "listen on arbitrary endpoint string X" and "connect on something completely different" is a little trickier.

All that said, as long as it's billed as an "expert" interface, it's still safer and better than the only path you have right now (which is "allow everything").

**Comment by balejk** [comment]
How about going the (default) ssh route and keeping the current solution
for listening ports (that is, assume loopback) but allow to specify a
host in addition to the port for the connection endpoints?

**Comment by meejah** [comment]
What I was thinking was to keep the current options as-is ("assume localhost" ports, as you say above) and making the "expert" interface just raw Twisted endpoint strings -- this would allow for "weirder" stuff like Tor endpoints, Onion services, and whatever else might be supported via plugins.

Maybe I need to play with it a little and see just how inconvenient shell-quoting etc becomes with the endpoint strings :)

Just so I'm 100% clear on your use-case, you want:

- you are on a device "outside" some org / network (lets say "laptop")
- you have a colleague on the "inside" who will run the other end of fowl (lets say "jumpbox")
- your end will listen on something (say, 2222)
- ...and forward to the jumpbox, asking for a connection on e.g. `"tcp:192.168.1.2:22"` to get to SSH on your desktop on the "inside" network
- so then you can "`ssh -p 2222 username@localhost`" on your laptop to get to your desktop inside

Is that approximately correct?

**Comment by balejk** [comment]
> What I was thinking was to keep the current options as-is ("assume localhost" ports, as you say above) and making the "expert" interface just raw Twisted endpoint strings -- this would allow for "weirder" stuff like Tor endpoints, Onion services, and whatever else might be supported via plugins.

That does sounds good, although I would still find it more convenient
for the non-expert options to allow connections outside localhost too as
it seems as a possibly fairly common use-case (perhaps I'm just biased
though). Plainly, the regular listen option would be just a port
(although I'm now wondering whether it might be better to also allow
specifying a bind address for symmetry and convenience) and the regular
connect option would be either a port, for which localhost would be
assumed, or a host:port combination, whereas the expert options would
take arbitrary Twisted endpoint strings.

Ultimately though, the important thing is what the protocol, rather than
the CLI, allows and it seems a bit strange to have an "expert" part of a
the fowld protocol. So perhaps it might make sense to always use the
Twisted endpoints in the protocol and only implement the above
assumptions/simplifications and "expert options" in the CLI?

One thought on this though: does Twisted (possibly via plugins that you
mention) support some endpoints where Twisted-specific syntax is used?
If so, perhaps it wouldn't be so ideal to use Twisted strings in the
protocol in case some other implementation emerges in the future which
will not be written in Python/using Twisted. In such a case, it would
probably also not be too convenient to rely on them for the CLI expert
options. Or are these strings always something reasonably portable and
parsable by other networking libraries?

On the other hand, it seems somewhat out-of-scope for the fowld protocol
to define syntax for various endpoints so I suppose even in the case
that the Twisted strings are custom, the fowld protocol endpoints could
simply be *defined* as "Twisted endpoint strings" and those supposed
alternative implementions would just have to deal with that as a part of
the protocol even if they were not based on Twisted.

> Is that approximately correct?

That is precisely correct :-)

**Comment by meejah** [comment]
> So perhaps it might make sense to always use the Twisted endpoints in the protocol and only implement the above assumptions/simplifications and "expert options" in the CLI?

Yes, this is how it is set up currently. That is, if you're an "integrator" speaking the `fowld` protocol you can do raw Twisted endpoint strings already today.

Although they're somewhat "twisted specific" they are just normal strings, they don't have async or "python-isms" burnt in.

I think maybe your instinct is right above -- a fairly straightforward and easy-to-understand upgrade to the CLI options would be to allow specifying the address (both bind and connect). This _can_ always be expanded in future to "full endpoint strings" if desired (but hard to go back the other way).

**Comment by balejk** [comment]
> > So perhaps it might make sense to always use the Twisted endpoints in the protocol and only implement the above assumptions/simplifications and "expert options" in the CLI?
>
> Yes, this is how it is set up currently. That is, if you're an "integrator" speaking the `fowld` protocol you can do raw Twisted endpoint strings already today.

Ah, so just to make sure, it is allowed by the protocol with which two
fowld instances talk to each other but it is not allowed by the protocol
by which fowld is controlled by the CLI (or some other program)?

> I think maybe your instinct is right above -- a fairly straightforward and easy-to-understand upgrade to the CLI options would be to allow specifying the address (both bind and connect). This _can_ always be expanded in future to "full endpoint strings" if desired (but hard to go back the other way).

Yes, that sounds very reasonable to me. I would even think that perhaps
the basic options need not be expanded beyond the address:port
combination and there could only be those --allow-listen/connect-raw
options instead. One could then use either the common address:port
options or use the "low-level" Twisted-endpoint-string options, rather
than gradually moving the "simple" options towards the "expert/raw" ones
by allowing additional Twisted strings one by one over time.

**Comment by meejah** [comment]
> Ah, so just to make sure, it is allowed by the protocol with which two fowld instances talk to each other but it is not allowed by the protocol by which fowld is controlled by the CLI (or some other program)?

Yes, exactly. See e.g. https://fowl.readthedocs.io/en/latest/frontend-protocol.html#input-kind-local

In fact, the CLI is simply talking to a `fowld`, but "in code" (it's not literally running a subprocess).

**Comment by balejk** [comment]
Yes, thank you, I got a little confused by the docs layout before,
specifically the "Permissions and Policy" section of protocol.rst: it
seems like this doesn't quite belong here? At the very least, the first
example of this section seems to be missing the "kind":
"grant-permission" field I believe.

**Comment by meejah** [comment]
Would happily merge doc improvements (or tickets saying what is confusing). Thanks!

**Comment by meejah** [comment]
Would love feedback on the "proposed UX" in the above draft PR. If you have other ideas for how to represent this in the CLI that'd be great.

**Comment by balejk** [comment]
For the "allow" flags it would seem more natural to me to just extend
the current ones rather than add new ones. If you would want to add the
option to specify raw Twisted endpoint strings in the future, there
would be three types of allow flags and that seems unnecessarily
complicated.

Similarly, I think the other two flags could simply be provided via the
existing -L/-R flags.

**Comment by meejah** [comment]
How? It already seems complex / possibly-confusing, especially with ":" as the separator. There's also the allow flags vs. the "listen here" flags too. So there's:

- `1234`
- `1234:22`
- `192.168.1.2:1234` (proposed?)
- `192.168.1.2:1234:22` (proposed?)
- `192.168.1.2:1234:192.168.5.4:22` (proposed?)

So, okay, the first two are relatively obvious (listen on 1234, and forward to 1234 or 22 respectively).

What does the third one do? It listens on a particular interface+port locally, what does it forward to? `localhost:1234`? `192.168.1.2:1234`? Similar question for the fourth.

The fifth is the most-obvious, I suppose, but ... that's a lot of ":"'s ;) and I didn't even do IPv6 examples.

**Comment by balejk** [comment]
I agree and I admit that I didn't consider IPv6, but do mind that the
new options proposed in your draft suffer the same issue with regard to
colons.

In the fourth example above I had in mind that it would default to
localhost if no address was specified, it seems to make more sense to
me.

And yes, I believe that mimicking the behaviour of SSH is the most
natural approach.

**Comment by meejah** [comment]
> In the fourth example above I had in mind that it would default to localhost if no address was specified, it seems to make more sense to me.

To be clear, you mean that `--local 192.168.1.2:1234:22` means "listen on port 1234 on interface 192.168.1.2 on the local computer" and then forward to "localhost:22 on the remote computer" right?

**Comment by meejah** [comment]
Although it's "somewhat harder to parse" with IPv6, they're delimited by square brackets, so "just a matter of programming".

I'll cook up a PR with the above, at least for IPv4, and see how it feels..?

**Comment by balejk** [comment]
> To be clear, you mean that `--local 192.168.1.2:1234:22` means "listen on port 1234 on interface 192.168.1.2 on the local computer" and then forward to "localhost:22 on the remote computer" right?

Exactly.

> I'll cook up a PR with the above, at least for IPv4, and see how it feels..?

Sounds good :-)

**Comment by meejah** [comment]
@balejk See https://github.com/meejah/fowl/pull/39 which I believe follows the "`ssh -L / -R`" paradigm to allow this use-case. Haven't done extensive testing, but should work enough to try it.

To install the experimental branch: `pip install git+https://github.com/meejah/fowl@37.bind-address`
